USE [master]
GO
/****** Object:  Database [asgard]    Script Date: 7/8/2019 9:58:21 PM ******/
CREATE DATABASE [asgard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'asgard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\asgard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'asgard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\asgard_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [asgard] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [asgard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [asgard] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [asgard] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [asgard] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [asgard] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [asgard] SET ARITHABORT OFF 
GO
ALTER DATABASE [asgard] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [asgard] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [asgard] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [asgard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [asgard] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [asgard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [asgard] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [asgard] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [asgard] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [asgard] SET  DISABLE_BROKER 
GO
ALTER DATABASE [asgard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [asgard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [asgard] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [asgard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [asgard] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [asgard] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [asgard] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [asgard] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [asgard] SET  MULTI_USER 
GO
ALTER DATABASE [asgard] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [asgard] SET DB_CHAINING OFF 
GO
ALTER DATABASE [asgard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [asgard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [asgard] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [asgard] SET QUERY_STORE = OFF
GO
USE [asgard]
GO
/****** Object:  Table [dbo].[Articulo]    Script Date: 7/8/2019 9:58:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Articulo](
	[NumPedido] [int] NOT NULL,
	[CodigoCerveza] [int] NOT NULL,
	[Cantidad] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cerveza]    Script Date: 7/8/2019 9:58:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cerveza](
	[CodigoCerveza] [int] NOT NULL,
	[Marca] [varchar](50) NOT NULL,
	[Tipo] [varchar](50) NOT NULL,
	[PaisOrigen] [varchar](50) NOT NULL,
	[GradosAlcohol] [int] NOT NULL,
 CONSTRAINT [PK_Cerveza] PRIMARY KEY CLUSTERED 
(
	[CodigoCerveza] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Client]    Script Date: 7/8/2019 9:58:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[DNIClient] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Nacionalidad] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[DNIClient] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedido]    Script Date: 7/8/2019 9:58:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedido](
	[NumPedido] [int] NOT NULL,
	[DNIClient] [int] NULL,
	[Fecha] [nchar](10) NULL,
	[Direccion] [nchar](100) NULL,
 CONSTRAINT [PK_Pedido] PRIMARY KEY CLUSTERED 
(
	[NumPedido] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Articulo]  WITH CHECK ADD  CONSTRAINT [FK_Articulo_Cerveza] FOREIGN KEY([CodigoCerveza])
REFERENCES [dbo].[Cerveza] ([CodigoCerveza])
GO
ALTER TABLE [dbo].[Articulo] CHECK CONSTRAINT [FK_Articulo_Cerveza]
GO
ALTER TABLE [dbo].[Articulo]  WITH CHECK ADD  CONSTRAINT [FK_Articulo_Pedido] FOREIGN KEY([NumPedido])
REFERENCES [dbo].[Pedido] ([NumPedido])
GO
ALTER TABLE [dbo].[Articulo] CHECK CONSTRAINT [FK_Articulo_Pedido]
GO
ALTER TABLE [dbo].[Pedido]  WITH CHECK ADD  CONSTRAINT [FK_Pedido_Client] FOREIGN KEY([DNIClient])
REFERENCES [dbo].[Client] ([DNIClient])
GO
ALTER TABLE [dbo].[Pedido] CHECK CONSTRAINT [FK_Pedido_Client]
GO
USE [master]
GO
ALTER DATABASE [asgard] SET  READ_WRITE 
GO
